### ISSUE TITLE
Keep getting and error!

### ISSUE THREAD

**Issue by Kbrenner** [impallari/Impallari-Fontlab-Macros#2]
Not sure what I'm doing wrong but I keep getting an error:

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
 File "E:\RoundCorners 05 8.py", line 75, in <module>
 RADIUS = Point(30,30)
 NameError: name 'Point' is not defined

its on running on WinXP

thanks

**Comment by impallari** [comment]
I have no idea whats going on.... sorry
